### ISSUE TITLE
Package doesn't support premium subscription on CoinGecko.

### ISSUE THREAD

**Issue by AhmedIbrahim336** [miscavage/CoinGecko-API#25]
We are trying to migrate from free to pro subscription in Coingecko API. this doesn't sound good. As we have to reimplement
the whole logic again. Another solution is to allow me to open a new pull request and implement the solution.

Coingecko is using another base URL for the pro subscription `http://pro-api.coingecko.com`
also, it requires you to add a param whenever you are using the API `x_cg_pro_api_key`. you will be given the token when you create a premium account. I already have one so I can implement the solution.
What do you think?

**Comment by nhausman1** [comment]
+1 to supporting this

**Comment by sachiew** [comment]
just a note that CoinGecko API paid plan is a different thing from CoinGecko Premium. 
CoinGecko Premium subscription has nothing to with API.
- https://www.coingecko.com/en/api/pricing
- https://www.coingecko.com/en/premium/pricing

**Comment by kevinweaver** [comment]
@AhmedIbrahim336 was this actually implemented? I need this functionality as well
